# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171106_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.CharField(max_length=3)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Equipo')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Medico')),
            ],
        ),
        migrations.AddField(
            model_name='medico',
            name='equipos',
            field=models.ManyToManyField(through='blog.Reservacion', to='blog.Equipo'),
        ),
    ]
