# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_reservacion_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
